spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

siem:
  log:
    sources:
      - path: /var/log/app
        type: NGINX
        pattern: "*.log"
  admin:
    username: ${SIEM_ADMIN_USERNAME}
    password: ${SIEM_ADMIN_PASSWORD}